### ISSUE TITLE
[V2] Backend

### ISSUE THREAD

**Issue by mdouchement** [FranckKe/mersea#129]
- [x] Rails API #126
- [x] Make old Rails Admin stuff compatible with Rails API #134
- [x] Mailer (password reset) #126
- [x] Geojson #135
- [x] Filtrable (e.g. filter pages on locale query) #135
  - Then reports can be filtered on `user_id` in order to displays it in the user's settings (!! Pundit !!)
- [x] Url slugs
- [x] Page category

**Comment by FranckKe** [comment]
[Rails admin question for rails api compatibility](https://stackoverflow.com/questions/36840247/using-rails-admin-with-rails-api)
